version: '3.0'
services:
  ubuntu:
      image: ubuntu:latest
      command : tail -f /bin/bash
      container_name: "ubuntu"
      links:
        - mongodb
      depends_on:
        - mongodb
  mongodb:
      image: mongo:latest
      container_name: "mongodb"
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - ./data/db:/data/db
      ports:
          - 28000:27017
      command: mongod --smallfiles --logpath=/dev/null # --quiet
  nodejs:
      build: ./docker-microservice/api          
      container_name : "node-app"
      volumes:
        - ./docker-microservice/api:/usr/src/app
        - /usr/src/app/node_modules
      ports :
        - 8080:8080
      links:
        - mongodb
      depends_on:
        - mongodb
  
